defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: ""
    values:
      layout: "default"
      description: "Thomas Junghans - Swiss based web application developer."