timezone: Europe/Zurich
author: "Thomas Junghans"
defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: ""
    values:
      layout: "default"
      description: "Swiss based web application developer."
  -
   scope:
      path: ""
      type: "posts" 
   values:
      layout: "post"